# GitHub Actions workflow for building and publishing the Java JAR as an artifact
name: Build and Publish JAR

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 18
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '18'

      - name: Build with maven
        run: mvn clean package -DskipTests

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: java-goodstack-svc-jar
          path: target/java-goodstack-svc-1.0.jar

      - name: Publish JAR to GitHub Packages
        run: mvn deploy -DskipTests --settings .github/maven-settings.xml
        # run: mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
